services:
  wg-easy:
    build:
      dockerfile: ./Dockerfile.dev
    entrypoint: ["/bin/sh", "-c"]
    command: ["sh /app/init-ifb.sh && exec pnpm run dev"]
    volumes:
      - ./src/:/app/
      - ./init-ifb.sh:/app/init-ifb.sh:ro
      - temp:/app/.nuxt/
      - temp1:/app/node_modules/
      - /lib/modules:/lib/modules:ro
      # - ./data/:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - INIT_ENABLED=true
      - INIT_HOST=localhost
      - INIT_PORT=51820
      - INIT_USERNAME=admin
      - INIT_PASSWORD=changeme
      - DEBUG=Database

# folders should be generated inside container
volumes:
  temp:
    driver: local
  temp1:
    driver: local
