// ! Auto Imports are not supported in this file

import { parseCidr } from 'cidr-tools';
import { stringifyIp } from 'ip-bigint';
import { removeNewlines, iptablesTemplate } from '../../utils/template';

import type { Hooks } from '../types';
import type { ClientType } from '#db/repositories/client/types';
import type { InterfaceType } from '#db/repositories/interface/types';
import type { UserConfigType } from '#db/repositories/userConfig/types';

type Options = {
  enableIpv6?: boolean;
};

export const configgen = {
  generateServerPeer: (
    client: Omit<ClientType, 'createdAt' | 'updatedAt'>,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const allowedIps = [
      `${client.ipv4Address}/32`,
      ...(enableIpv6 ? [`${client.ipv6Address}/128`] : []),
      ...(client.serverAllowedIps ?? []),
    ];

    const extraLines = [];
    if (client.serverEndpoint) {
      extraLines.push(`Endpoint = ${client.serverEndpoint}`);
    }

    return `# Client: ${client.name} (${client.id})
[Peer]
PublicKey = ${client.publicKey}
PresharedKey = ${client.preSharedKey}
AllowedIPs = ${allowedIps.join(', ')}${extraLines.length ? `\n${extraLines.join('\n')}` : ''}`;
  },

  generateServerInterface: (
    wgInterface: InterfaceType,
    hooks: Hooks,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const cidr4 = parseCidr(wgInterface.ipv4Cidr);
    const cidr6 = parseCidr(wgInterface.ipv6Cidr);
    const ipv4Addr = stringifyIp({ number: cidr4.start + 1n, version: 4 });
    const ipv6Addr = stringifyIp({ number: cidr6.start + 1n, version: 6 });

    const address =
      `${ipv4Addr}/${cidr4.prefix}` +
      (enableIpv6 ? `, ${ipv6Addr}/${cidr6.prefix}` : '');

    const parameters = {
      Jc: wgInterface.jC,
      Jmin: wgInterface.jMin,
      Jmax: wgInterface.jMax,
      S1: wgInterface.s1,
      S2: wgInterface.s2,
      S3: wgInterface.s3,
      S4: wgInterface.s4,
      H1: wgInterface.h1,
      H2: wgInterface.h2,
      H3: wgInterface.h3,
      H4: wgInterface.h4,
      I1: wgInterface.i1,
      I2: wgInterface.i2,
      I3: wgInterface.i3,
      I4: wgInterface.i4,
      I5: wgInterface.i5,
    } as const;

    const awgLines = Object.entries(parameters)
      .filter(([_, value]) => !!value)
      .map(([key, value]) => `${key} = ${value}`);

    return `# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${wgInterface.privateKey}
Address = ${address}
ListenPort = ${wgInterface.port}
MTU = ${wgInterface.mtu}
${awgLines.length ? `${awgLines.join('\n')}\n` : ''}
PreUp = ${iptablesTemplate(hooks.preUp, wgInterface)}
PostUp = ${iptablesTemplate(hooks.postUp, wgInterface)}
PreDown = ${iptablesTemplate(hooks.preDown, wgInterface)}
PostDown = ${iptablesTemplate(hooks.postDown, wgInterface)}`;
  },

  generateClientConfig: (
    wgInterface: InterfaceType,
    userConfig: UserConfigType,
    client: ClientType,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const address =
      `${client.ipv4Address}/32` +
      (enableIpv6 ? `, ${client.ipv6Address}/128` : '');

    const hookLines = [
      client.preUp ? `PreUp = ${removeNewlines(client.preUp)}` : null,
      client.postUp ? `PostUp = ${removeNewlines(client.postUp)}` : null,
      client.preDown ? `PreDown = ${removeNewlines(client.preDown)}` : null,
      client.postDown ? `PostDown = ${removeNewlines(client.postDown)}` : null,
    ];

    const allDnsServers = client.dns ?? userConfig.defaultDns;
    // Filter out IPv6 DNS when IPv6 is disabled to avoid resolution issues
    const dnsServers = enableIpv6
      ? allDnsServers
      : allDnsServers.filter((ip: string) => !ip.includes(':'));
    const dnsLine =
      dnsServers.length > 0 ? `DNS = ${dnsServers.join(', ')}` : null;

    const parameters = {
      Jc: client.jC ?? wgInterface.jC,
      Jmin: client.jMin ?? wgInterface.jMin,
      Jmax: client.jMax ?? wgInterface.jMax,
      S1: wgInterface.s1,
      S2: wgInterface.s2,
      S3: wgInterface.s3,
      S4: wgInterface.s4,
      H1: wgInterface.h1,
      H2: wgInterface.h2,
      H3: wgInterface.h3,
      H4: wgInterface.h4,
      I1: client.i1 ?? wgInterface.i1,
      I2: client.i2 ?? wgInterface.i2,
      I3: client.i3 ?? wgInterface.i3,
      I4: client.i4 ?? wgInterface.i4,
      I5: client.i5 ?? wgInterface.i5,
    } as const;

    const awgLines = Object.entries(parameters)
      .filter(([_, value]) => !!value)
      .map(([key, value]) => `${key} = ${value}`);

    const extraLines = [dnsLine, ...hookLines, ...awgLines].filter(
      (v) => v !== null
    );

    return `[Interface]
PrivateKey = ${client.privateKey}
Address = ${address}
MTU = ${client.mtu}
${extraLines.length ? `${extraLines.join('\n')}\n` : ''}
[Peer]
PublicKey = ${wgInterface.publicKey}
PresharedKey = ${client.preSharedKey}
AllowedIPs = ${(client.allowedIps ?? userConfig.defaultAllowedIps).join(', ')}
PersistentKeepalive = ${client.persistentKeepalive}
Endpoint = ${userConfig.host}:${userConfig.port}`;
  },

  cleanClientFilename(name: string): string {
    return name
      .replace(/[^a-zA-Z0-9_=+.-]/g, '-')
      .replace(/(-{2,}|-$)/g, '-')
      .replace(/-$/, '')
      .substring(0, 32);
  },
};
