<template>
  <BaseDialog>
    <template #trigger><slot /></template>
    <template #title>
      {{
        mode === 'create'
          ? $t('admin.trafficGroups.create')
          : $t('admin.trafficGroups.edit')
      }}
    </template>
    <template #description>
      <div class="flex flex-col gap-4">
        <FormTextField
          id="name"
          v-model="formData.name"
          :label="$t('admin.trafficGroups.name')"
        />

        <!-- Speed Limits Section -->
        <div>
          <p class="mb-1 text-sm font-medium">
            {{ $t('admin.trafficGroups.speedLimits') }}
          </p>
          <FormSwitchField
            id="unlimitedSpeed"
            v-model="unlimitedSpeed"
            :label="$t('admin.trafficGroups.unlimitedSpeed')"
          />
        </div>

        <template v-if="!unlimitedSpeed">
          <FormNumberField
            id="upKbps"
            v-model.number="formData.upKbps"
            :label="$t('admin.trafficGroups.uploadKbps')"
          />
          <FormNumberField
            id="downKbps"
            v-model.number="formData.downKbps"
            :label="$t('admin.trafficGroups.downloadKbps')"
          />
        </template>

        <!-- Quota Section -->
        <div>
          <p class="mb-1 text-sm font-medium">
            {{ $t('admin.trafficGroups.quota') }}
          </p>
          <FormSwitchField
            id="noQuota"
            v-model="noQuota"
            :label="$t('admin.trafficGroups.noQuota')"
          />
        </div>

        <template v-if="!noQuota">
          <FormNumberField
            id="quotaLimitBytes"
            v-model.number="quotaLimitMB"
            :label="$t('admin.trafficGroups.quotaLimitMB')"
          />
          <div>
            <p class="mb-1 text-sm font-medium">
              {{ $t('admin.trafficGroups.period') }}
            </p>
            <select
              v-model="formData.quotaPeriod"
              class="w-full rounded border border-gray-300 px-3 py-2 dark:border-neutral-600 dark:bg-neutral-800"
            >
              <option value="daily">
                {{ $t('admin.trafficGroups.daily') }}
              </option>
              <option value="weekly">
                {{ $t('admin.trafficGroups.weekly') }}
              </option>
              <option value="monthly">
                {{ $t('admin.trafficGroups.monthly') }}
              </option>
            </select>
          </div>
          <FormSwitchField
            id="quotaAutoDisable"
            v-model="formData.quotaAutoDisable"
            :label="$t('admin.trafficGroups.autoDisable')"
          />
        </template>

        <!-- Color Preview -->
        <div v-if="mode === 'create'">
          <p class="mb-1 text-sm font-medium">
            {{ $t('admin.trafficGroups.colorPreview') }}
          </p>
          <span class="text-sm text-gray-600 dark:text-gray-400">
            {{ $t('admin.trafficGroups.autoGenerated') }}
          </span>
        </div>
      </div>
    </template>
    <template #actions>
      <DialogClose as-child>
        <BaseSecondaryButton>{{ $t('dialog.cancel') }}</BaseSecondaryButton>
      </DialogClose>
      <DialogClose as-child>
        <BasePrimaryButton @click="handleSave">
          {{ mode === 'create' ? $t('dialog.create') : $t('dialog.save') }}
        </BasePrimaryButton>
      </DialogClose>
    </template>
  </BaseDialog>
</template>

<script setup lang="ts">
type TrafficGroupFormValue = {
  name: string;
  upKbps: number | null;
  downKbps: number | null;
  quotaLimitBytes: number | null;
  quotaPeriod: 'daily' | 'weekly' | 'monthly' | null;
  quotaAutoDisable: boolean | null;
};

const props = defineProps<{
  mode: 'create' | 'edit';
  group?: TrafficGroupFormValue;
}>();

const emit = defineEmits<{
  save: [
    data: {
      name: string;
      upKbps?: number;
      downKbps?: number;
      quotaLimitBytes?: number;
      quotaPeriod?: 'daily' | 'weekly' | 'monthly';
      quotaAutoDisable?: boolean;
    },
  ];
}>();

type TrafficGroupSaveData = {
  name: string;
  upKbps?: number;
  downKbps?: number;
  quotaLimitBytes?: number;
  quotaPeriod?: 'daily' | 'weekly' | 'monthly';
  quotaAutoDisable?: boolean;
};

const formData = reactive({
  name: props.group?.name || '',
  upKbps: props.group?.upKbps || undefined,
  downKbps: props.group?.downKbps || undefined,
  quotaLimitBytes: props.group?.quotaLimitBytes || undefined,
  quotaPeriod: props.group?.quotaPeriod || 'monthly',
  quotaAutoDisable: props.group?.quotaAutoDisable ?? true,
});

const unlimitedSpeed = ref(!props.group?.upKbps && !props.group?.downKbps);
const noQuota = ref(!props.group?.quotaLimitBytes);

const quotaLimitMB = computed({
  get: () =>
    formData.quotaLimitBytes
      ? Math.round(formData.quotaLimitBytes / (1024 * 1024))
      : undefined,
  set: (val) => {
    formData.quotaLimitBytes = val ? val * 1024 * 1024 : undefined;
  },
});

function handleSave() {
  const data: TrafficGroupSaveData = {
    name: formData.name,
  };

  if (!unlimitedSpeed.value) {
    data.upKbps = formData.upKbps;
    data.downKbps = formData.downKbps;
  }

  if (!noQuota.value) {
    data.quotaLimitBytes = formData.quotaLimitBytes;
    data.quotaPeriod = formData.quotaPeriod;
    data.quotaAutoDisable = formData.quotaAutoDisable;
  }

  emit('save', data);
}
</script>
