<template>
  <BaseDialog>
    <template #trigger><slot /></template>
    <template #title>
      {{ mode === 'create' ? $t('admin.trafficGroups.create') : $t('admin.trafficGroups.edit') }}
    </template>
    <template #description>
      <FormGroup>
        <FormTextField
          id="name"
          v-model="formData.name"
          :label="$t('admin.trafficGroups.name')"
        />

        <!-- Speed Limits Section -->
        <FormElement>
          <FormLabel>{{ $t('admin.trafficGroups.speedLimits') }}</FormLabel>
          <FormSwitchField
            id="unlimitedSpeed"
            v-model="unlimitedSpeed"
            :label="$t('admin.trafficGroups.unlimitedSpeed')"
          />
        </FormElement>

        <template v-if="!unlimitedSpeed">
          <FormTextField
            id="upKbps"
            v-model.number="formData.upKbps"
            type="number"
            :label="$t('admin.trafficGroups.uploadKbps')"
          />
          <FormTextField
            id="downKbps"
            v-model.number="formData.downKbps"
            type="number"
            :label="$t('admin.trafficGroups.downloadKbps')"
          />
        </template>

        <!-- Quota Section -->
        <FormElement>
          <FormLabel>{{ $t('admin.trafficGroups.quota') }}</FormLabel>
          <FormSwitchField
            id="noQuota"
            v-model="noQuota"
            :label="$t('admin.trafficGroups.noQuota')"
          />
        </FormElement>

        <template v-if="!noQuota">
          <FormTextField
            id="quotaLimitBytes"
            v-model.number="quotaLimitMB"
            type="number"
            :label="$t('admin.trafficGroups.quotaLimitMB')"
          />
          <FormElement>
            <FormLabel>{{ $t('admin.trafficGroups.period') }}</FormLabel>
            <select
              v-model="formData.quotaPeriod"
              class="w-full rounded border border-gray-300 px-3 py-2 dark:border-neutral-600 dark:bg-neutral-800"
            >
              <option value="daily">{{ $t('admin.trafficGroups.daily') }}</option>
              <option value="weekly">{{ $t('admin.trafficGroups.weekly') }}</option>
              <option value="monthly">{{ $t('admin.trafficGroups.monthly') }}</option>
            </select>
          </FormElement>
          <FormSwitchField
            id="quotaAutoDisable"
            v-model="formData.quotaAutoDisable"
            :label="$t('admin.trafficGroups.autoDisable')"
          />
        </template>

        <!-- Color Preview -->
        <FormElement v-if="mode === 'create'">
          <FormLabel>{{ $t('admin.trafficGroups.colorPreview') }}</FormLabel>
          <div class="flex gap-2">
            <span class="text-sm text-gray-600 dark:text-gray-400">
              {{ $t('admin.trafficGroups.autoGenerated') }}
            </span>
          </div>
        </FormElement>
      </FormGroup>
    </template>
    <template #actions>
      <DialogClose as-child>
        <BaseSecondaryButton>{{ $t('dialog.cancel') }}</BaseSecondaryButton>
      </DialogClose>
      <DialogClose as-child>
        <BasePrimaryButton @click="handleSave">
          {{ mode === 'create' ? $t('dialog.create') : $t('dialog.save') }}
        </BasePrimaryButton>
      </DialogClose>
    </template>
  </BaseDialog>
</template>

<script setup lang="ts">
import type { TrafficGroupType } from '#db/repositories/trafficGroup/types';

const props = defineProps<{
  mode: 'create' | 'edit';
  group?: TrafficGroupType;
}>();

const emit = defineEmits<{
  save: [data: {
    name: string;
    upKbps?: number;
    downKbps?: number;
    quotaLimitBytes?: number;
    quotaPeriod?: 'daily' | 'weekly' | 'monthly';
    quotaAutoDisable?: boolean;
  }];
}>();

const formData = reactive({
  name: props.group?.name || '',
  upKbps: props.group?.upKbps || undefined,
  downKbps: props.group?.downKbps || undefined,
  quotaLimitBytes: props.group?.quotaLimitBytes || undefined,
  quotaPeriod: props.group?.quotaPeriod || 'monthly',
  quotaAutoDisable: props.group?.quotaAutoDisable ?? true,
});

const unlimitedSpeed = ref(!props.group?.upKbps && !props.group?.downKbps);
const noQuota = ref(!props.group?.quotaLimitBytes);

const quotaLimitMB = computed({
  get: () => formData.quotaLimitBytes ? Math.round(formData.quotaLimitBytes / (1024 * 1024)) : undefined,
  set: (val) => {
    formData.quotaLimitBytes = val ? val * 1024 * 1024 : undefined;
  },
});

function handleSave() {
  const data: any = {
    name: formData.name,
  };

  if (!unlimitedSpeed.value) {
    data.upKbps = formData.upKbps;
    data.downKbps = formData.downKbps;
  }

  if (!noQuota.value) {
    data.quotaLimitBytes = formData.quotaLimitBytes;
    data.quotaPeriod = formData.quotaPeriod;
    data.quotaAutoDisable = formData.quotaAutoDisable;
  }

  emit('save', data);
}
</script>
